### ISSUE TITLE
Type error in test case ptr6.tip

### ISSUE THREAD

**Issue by aobo-y** [matthewbdwyer/tipc#1]
Variable `y` in test case https://github.com/matthewbdwyer/tipc/blob/master/test/ptr6.tip has type conflict

The Line #6-7 implies that `y` is 
- a `ptr to an unknown ptr (null)`
- a `ptr to integer (13)`

```
  y = alloc null;
  *y = 13;
```
Without type analysis, it can run in both `tipc` and `TIP` with no crush. I guess it works in `tipc` because both types are compiled to `int64`.

Is this a dedicated type-error test case?

**Comment by matthewbdwyer** [comment]
Fixed in the new release.
