### ISSUE TITLE
llvm10 is no longer available in homebrew

### ISSUE THREAD

**Issue by nicholasphair** [matthewbdwyer/tipc#13]
The latest stable release of llvm in homebrew has been upgraded to 11 and there is no alias to llvm10 available. This impacted at least one student building on mac. This seems like a bug/oversight in the homebrew formula - I'm hoping it will be fixed shortly. If not, we will have to find another way to install llvm10 or bump to 11.

To recreate, from a mac, run,
```bash
./bin/bootstrap.sh
...
Error: No available formula or cask with the name "llvm@10".
==> Searching for a previously deleted formula (in the last month)...
```

Relevant links:
brew docs: https://formulae.brew.sh/formula/llvm (notice no mention of llvm10)
git history: https://github.com/Homebrew/homebrew-core/commits/master/Formula/llvm.rb (notice the bump to 11 about a week ago)

**Comment by matthewbdwyer** [comment]
Is tipc incompatible with llvm11?  I haven't tried it and I'm not familiar with the API changes.

**Comment by nicholasphair** [comment]
Looks like there were some breaking api changes we will have to work through on v11. 
```bash
[/opt/cs6620/repos/tipc/build]
nickphair@Nicks-MacBook-Pro:$ cmake ../
...
[  4%] Building CXX object src/semantic/types/CMakeFiles/types.dir/TypeInference.cpp.o
/opt/cs6620/repos/tipc/src/codegen/CodeGenFunctions.cpp:414:30: error: no matching function for call to 'CreateEntryBlockAlloca'
      AllocaInst *argAlloc = CreateEntryBlockAlloca(TheFunction, arg.getName());
```

I wouldn't recommend upgrading your brew package atm. The upgrade removed v10 and I don't immediately know of a way of getting it back.

**Comment by nicholasphair** [comment]
actually, we should be able to install from the old commit id. I'll just have to find the right switches for brew. It can be a stopgap until upgraded to 11.

**Comment by nicholasphair** [comment]
I've submitted a PR to homebrew-core to get v10 back (https://github.com/Homebrew/homebrew-core/pull/63938)

2 previous PRs by other folks trying to tackle the same issue were shot down. They didn't put up much of a fight though so hopefully my PR is a bit more convincing.
