### ISSUE TITLE
 ./bin/bootstrap.sh command gets stuck, doesnt print any error message 

### ISSUE THREAD

**Issue by soneyahossain** [matthewbdwyer/tipc#30]
We discussed this issue in the slack group, and it looks like the command waits for the Sudo password. Perhaps printing a message that asks for the password would help?

**Comment by nicholasphair** [comment]
@soneyahossain do you want to take a look at the PR for this?

**Comment by soneyahossain** [comment]
sure, I though Prof. Matt will take care of the pull request.

**Comment by matthewbdwyer** [comment]
Soneya - let me know when you have verified that this works for you.  I think I need to merge this PR to get the builds working again.

**Comment by soneyahossain** [comment]
I have checked on my machine and I think the fix is not  working, here is the error log 

soneya@soneya-Thelio:~/tipc-bootstrap_fix$ ./bin/bootstrap.sh
+ declare -r ANTLR_VERSION=4
+ declare -r JAVA_VERSION=8
+ declare -r LLVM_VERSION=11
++ git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git
+ declare -r ROOT_DIR=
+ bootstrap
++ uname -s
+ local unameOut=Linux
+ case "${unameOut}" in
+ bootstrap_linux
+ . /etc/os-release
++ NAME=Ubuntu
++ VERSION='20.04.2 LTS (Focal Fossa)'
++ ID=ubuntu
++ ID_LIKE=debian
++ PRETTY_NAME='Ubuntu 20.04.2 LTS'
++ VERSION_ID=20.04
++ HOME_URL=https://www.ubuntu.com/
++ SUPPORT_URL=https://help.ubuntu.com/
++ BUG_REPORT_URL=https://bugs.launchpad.net/ubuntu/
++ PRIVACY_POLICY_URL=https://www.ubuntu.com/legal/terms-and-policies/privacy-policy
++ VERSION_CODENAME=focal
++ UBUNTU_CODENAME=focal
+ '[' ubuntu == ubuntu -o ubuntu == pop ']'
+ bootstrap_ubuntu
+ bootstrap_ubuntu_dependencies
+ '[' -d /usr/share/keyrings ']'
+ wget https://apt.corretto.aws/corretto.key
--2021-08-15 13:36:44--  https://apt.corretto.aws/corretto.key
Resolving apt.corretto.aws (apt.corretto.aws)... 99.84.110.49, 99.84.110.67, 99.84.110.50, ...
Connecting to apt.corretto.aws (apt.corretto.aws)|99.84.110.49|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1695 (1.7K) [binary/octet-stream]
Saving to: ‘corretto.key’

corretto.key        100%[===================>]   1.66K  --.-KB/s    in 0s      

2021-08-15 13:36:44 (562 MB/s) - ‘corretto.key’ saved [1695/1695]

+ gpg --dearmor corretto.key
+ sudo mv corretto.key.gpg /usr/share/keyrings/amazon-corretto-8-keyring.gpg
[sudo] password for soneya: 
+ sudo cp /bin/apt/amazon-corretto-8.sources /etc/apt/sources.list.d/
cp: cannot stat '/bin/apt/amazon-corretto-8.sources': Not a directory
