### ISSUE TITLE
CMake Deprecation Warning [Compatibility with CMake < 2.8.12]

### ISSUE THREAD

**Issue by pennbauman** [matthewbdwyer/tipc#48]
Building the project with `make` (but not running `cmake ..`) produces the following warning each time.

	CMake Deprecation Warning at CMakeLists.txt:2 (cmake_minimum_required):
	  Compatibility with CMake < 2.8.12 will be removed from a future version of
	  CMake.
	
	  Update the VERSION argument <min> value or use a ...<max> suffix to tell
	  CMake that the project does not need compatibility with older versions.
	
	
	-- Building without demo. To enable demo build use: -DWITH_DEMO=True
	CMake Deprecation Warning at CMakeLists.txt:31 (CMAKE_POLICY):
	  The OLD behavior for policy CMP0054 will be removed from a future version
	  of CMake.
	
	  The cmake-policies(7) manual explains that the OLD behaviors of all
	  policies are deprecated and that a policy should be set to OLD only under
	  specific short-term circumstances.  Projects should be ported to the NEW
	  behavior and not rely on setting a policy to OLD.
	
	
	CMake Deprecation Warning at CMakeLists.txt:32 (CMAKE_POLICY):
	  The OLD behavior for policy CMP0045 will be removed from a future version
	  of CMake.
	
	  The cmake-policies(7) manual explains that the OLD behaviors of all
	  policies are deprecated and that a policy should be set to OLD only under
	  specific short-term circumstances.  Projects should be ported to the NEW
	  behavior and not rely on setting a policy to OLD.
	
	
	CMake Deprecation Warning at CMakeLists.txt:33 (CMAKE_POLICY):
	  The OLD behavior for policy CMP0042 will be removed from a future version
	  of CMake.
	
	  The cmake-policies(7) manual explains that the OLD behaviors of all
	  policies are deprecated and that a policy should be set to OLD only under
	  specific short-term circumstances.  Projects should be ported to the NEW
	  behavior and not rely on setting a policy to OLD.
	
	
	CMake Deprecation Warning at CMakeLists.txt:38 (CMAKE_POLICY):
	  The OLD behavior for policy CMP0059 will be removed from a future version
	  of CMake.
	
	  The cmake-policies(7) manual explains that the OLD behaviors of all
	  policies are deprecated and that a policy should be set to OLD only under
	  specific short-term circumstances.  Projects should be ported to the NEW
	  behavior and not rely on setting a policy to OLD.
	
	
	CMake Deprecation Warning at CMakeLists.txt:39 (CMAKE_POLICY):
	  The OLD behavior for policy CMP0054 will be removed from a future version
	  of CMake.
	
	  The cmake-policies(7) manual explains that the OLD behaviors of all
	  policies are deprecated and that a policy should be set to OLD only under
	  specific short-term circumstances.  Projects should be ported to the NEW
	  behavior and not rely on setting a policy to OLD.

**Comment by nicholasphair** [comment]
Hi @pennbauman, we are generally aware of these warnings, you can actually see them in the build pipeline. We will work to clean them up in the future.

Nevertheless, care to give some more details. If only to round out the issue. What os? What version of cmake? What commands are you running? There are all good things to share.

**Comment by pennbauman** [comment]
I'm using Ubuntu 20.04.1 (Kernel 5.11.0-1016) with CMake 3.21.1, and the errors only appear of me while running `make` (within the `build` directory). 

Looking at the errors in more detail they seem to be originating from `build/antlr4_runtime/src/antlr4_runtime/runtime/Cpp/CMakeLists.txt` specifically lines 28-40:

	if(CMAKE_VERSION VERSION_EQUAL "3.0.0" OR
	   CMAKE_VERSION VERSION_GREATER "3.0.0")
	  CMAKE_POLICY(SET CMP0026 NEW)
	  CMAKE_POLICY(SET CMP0054 OLD)
	  CMAKE_POLICY(SET CMP0045 OLD)
	  CMAKE_POLICY(SET CMP0042 OLD)
	endif()

	if(CMAKE_VERSION VERSION_EQUAL "3.3.0" OR
	   CMAKE_VERSION VERSION_GREATER "3.3.0")
	  CMAKE_POLICY(SET CMP0059 OLD)
	  CMAKE_POLICY(SET CMP0054 OLD)
	endif()

**Comment by nicholasphair** [comment]
Are they errors or warnings?

**Comment by pennbauman** [comment]
They're warnings produced directly be CMake, so they shouldn't be effected by compiler settings.

**Comment by nicholasphair** [comment]
Okay, thanks for submitting the issue. We planned on addressing more of these cmake warnings on the next development iteration so they probably won't be a cleaned up until then. In the meantime, happy to accept a pr :)

**Comment by matthewbdwyer** [comment]
A bit more investigation revealed that these warnings are actually due to the antlr_runtime cmake support.   They are explicitly setting the policy directives, which gives rise to the warnings.   When they update their cmake files these messages will go away, but this is not a tipc specific problem.    We may want to fix their cmake files and push upstream to resolve this, but it is not a priority.
