### ISSUE TITLE
Implement premature stopping for compiler phases

### ISSUE THREAD

**Issue by will-leeson** [matthewbdwyer/tipc#53]
To assist with grading and debugging, we want to add a measure to stop the compiler at different phases and output the results. I.E. stop after type checking is done to ensure the right types are generated.

**Comment by matthewbdwyer** [comment]
@will-leeson A lot of this functionality can be achieved using existing options, e.g., --pt will stop after type checking.   What additional functionality do you think is required?

**Comment by will-leeson** [comment]
I believe this was to deal with test brittleness for the autograder. The idea was to dump the internal representation of the types instead of the pretty printed which can change based on a variety of implementation details. Will --pt allow for this?

**Comment by matthewbdwyer** [comment]
I can see how the naming of type variables, e.g., alphas, can change the textual representation.  I guess the question is what would a better format be?

**Comment by will-leeson** [comment]
I'm not certain as I haven't dealt with the type checker much. Is there a way to have the pretty printer be implemented by us and then they handle what is given to the pretty printer?

**Comment by matthewbdwyer** [comment]
That's kind of how things work currently, but of course they have to extend the pretty printer and this can lead to differences in the textual form.  I suppose we could overwrite their extension, but to make this work seamlessly we would have to make sure that the APIs we rely on had no wiggle room, i.e., we define the names/signatures of the functions.   

We will have to think more about this.
