### ISSUE TITLE
Add zsh support

### ISSUE THREAD

**Issue by FriendlyAI** [matthewbdwyer/tipc#63]
As zsh is now the default shell on macOS, the bootstrap script should be able to set environment variables in `~/.zprofile`.

**Comment by joek13** [comment]
Created a PR using `zshrc` instead of `zprofile`, since we already use `bashrc` in `bin/bootstrap.sh`.

**Comment by matthewbdwyer** [comment]
Updated bootstrap to use .zshrc on the mac
